# Generated by Django 4.0.5 on 2022-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('resourceId', models.CharField(max_length=30)),
                ('resourceUri', models.CharField(max_length=300)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
