# Generated by Django 4.0.5 on 2022-06-16 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField()),
                ('usd_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_time', models.DateTimeField()),
                ('rub_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
