# Generated by Django 4.0.5 on 2022-06-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
